### ISSUE TITLE
windows build fails due to missing GID UID

### ISSUE THREAD

**Issue by gpongelli** [abegosum/openlensbuilder#2]
Hi,
when building on windows 11 with `docker compose up win-builder` , due to missing `${APP_USER_UID}` and `${APP_USER_GID}` the build fails as you can see
![win-builder](https://github.com/abegosum/openlensbuilder/assets/842026/8b7e607f-2a7a-4c48-bc39-73fa8b17f44f)

the fix consist adding a default value for both env var into docker-compose.yml:
```yaml
  win-builder:
    build:
      context: ./win-builder/
      args:
        - APP_USER_UID=${APP_USER_UID:-8000}
        - APP_GROUP_GID=${APP_GROUP_GID:-8000}
```
